checks:
  required_workflows:
    clean.yaml: False
    audit.yaml: False
    backport.yaml: False
    codeql.yaml: False
  codespell:
    ignore_re:
      - node_modules/.*
  dependabot_config:
    ignore_version_files:
      - node_modules/@actions/core/package.json
